### ISSUE TITLE
getHostsPerf.py and getVMPerf.py not working in xenserver 6.5

### ISSUE THREAD

**Issue by andrewferdinandus** [jri-sp/Graylog_XenServer#1]
ERROR: Traceback (most recent call last):
  File "./getVMPerf.py", line 19, in ?
    perf_data = XenServer().get_rrd_data(hostname)
  File "/root/Graylog_XenServer/XenServer.py", line 36, in get_rrd_data
    rrd_data.refresh(rrd_url,rrd_parameters)
  File "/root/Graylog_XenServer/parse_rrd.py", line 112, in refresh
    sock = urllib.URLopener().open(url)
  File "/usr/lib64/python2.4/urllib.py", line 190, in open
    return getattr(self, name)(url)
  File "/usr/lib64/python2.4/urllib.py", line 313, in open_http
    h.endheaders()
  File "/usr/lib64/python2.4/httplib.py", line 804, in endheaders
    self._send_output()
  File "/usr/lib64/python2.4/httplib.py", line 685, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.4/httplib.py", line 652, in send
    self.connect()
  File "/usr/lib64/python2.4/httplib.py", line 620, in connect
    socket.SOCK_STREAM):
IOError: [Errno socket error] (-2, 'Name or service not known')

Same error occurred either scripts.

**Comment by jri-sp** [comment]
Hi @andrewferdinandus ,

Thanks for pointing me this! 
I don't have a XenServer 6.5 but I've reproduced the same thing on 6.2.

I think it's due to a wrong hostname in the pool's host list (equivalent to `xe host-list`).
So I had a try/except (https://github.com/jri-sp/Graylog_XenServer/commit/42b1346033a2666abe0b2ef9a8ba42a48bf2d250) to not crash the script when a host can't be contacted (wrong hostname, shutdown host, connectivity issues, etc.).
I also use IP address now to connect to the hosts, to avoid hostname issues.

Let me know if it can help you.

Regards
